# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screener.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 781, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 781, 351))
        self.tableView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 470, 781, 80))
        self.widget.setObjectName("widget")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(350, 30, 118, 23))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(129, 30, 181, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(580, 10, 110, 71))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuDownload = QtWidgets.QMenu(self.menubar)
        self.menuDownload.setObjectName("menuDownload")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDownload_Historical_Data = QtWidgets.QAction(MainWindow)
        self.actionDownload_Historical_Data.setObjectName("actionDownload_Historical_Data")
        self.actionDownload_Stock_Prices = QtWidgets.QAction(MainWindow)
        self.actionDownload_Stock_Prices.setObjectName("actionDownload_Stock_Prices")
        self.actionSearch_by_Symbol = QtWidgets.QAction(MainWindow)
        self.actionSearch_by_Symbol.setObjectName("actionSearch_by_Symbol")
        self.actionSearch_by_Name = QtWidgets.QAction(MainWindow)
        self.actionSearch_by_Name.setObjectName("actionSearch_by_Name")
        self.actionDownload_Information = QtWidgets.QAction(MainWindow)
        self.actionDownload_Information.setObjectName("actionDownload_Information")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuDownload.addAction(self.actionDownload_Historical_Data)
        self.menuDownload.addAction(self.actionDownload_Stock_Prices)
        self.menuFilter.addAction(self.actionSearch_by_Symbol)
        self.menuFilter.addAction(self.actionSearch_by_Name)
        self.menuInfo.addAction(self.actionDownload_Information)
        self.menuInfo.addAction(self.actionAbout)
        self.menubar.addAction(self.menuDownload.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stock Screener"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "List View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Detail View"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox.setText(_translate("MainWindow", "I Own"))
        self.checkBox_2.setText(_translate("MainWindow", "Watchlist"))
        self.menuDownload.setTitle(_translate("MainWindow", "Download"))
        self.menuFilter.setTitle(_translate("MainWindow", "Search"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionDownload_Historical_Data.setText(_translate("MainWindow", "Download Historical Data"))
        self.actionDownload_Stock_Prices.setText(_translate("MainWindow", "Download Stock Prices"))
        self.actionSearch_by_Symbol.setText(_translate("MainWindow", "Search by Symbol"))
        self.actionSearch_by_Name.setText(_translate("MainWindow", "Search by Name"))
        self.actionDownload_Information.setText(_translate("MainWindow", "Download Information"))
        self.actionAbout.setText(_translate("MainWindow", "Software Info"))

